# Generated by Django 3.0.6 on 2022-08-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ocupation',
            field=models.CharField(blank=True, choices=[('0', 'Administrador'), ('1', 'Almacen'), ('2', 'Ventas'), ('3', 'Producción')], max_length=1),
        ),
    ]
