# Generated by Django 3.0.6 on 2022-08-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_carshop_number_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='carshop',
            name='sub_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='saledetail',
            name='sub_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Subtotal'),
        ),
    ]
