# Generated by Django 3.0.6 on 2022-09-06 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0006_auto_20220829_0342'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('f_name', models.CharField(max_length=100, verbose_name='Primer apellido')),
                ('l_name', models.CharField(max_length=100, verbose_name='Segundo Apellido')),
                ('nickname', models.CharField(max_length=100, verbose_name='Usuario')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date_order_start', models.DateTimeField(verbose_name='Fecha de Venta')),
                ('cod', models.CharField(max_length=13, unique=True, verbose_name='codigo de orden')),
                ('count', models.PositiveIntegerField(verbose_name='Cantidad de Productos')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('pay_ammount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto dejado')),
                ('pend_ammount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pendiente')),
                ('total_pay', models.BooleanField(default=False, verbose_name='Pagada')),
                ('date_order', models.DateField(verbose_name='Fecha de entrega de pedido')),
                ('complete', models.BooleanField(default=False, verbose_name='Pedido completo')),
                ('anulate', models.BooleanField(default=False, verbose_name='Venta Anulada')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='orders.Client', verbose_name='Cliente')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='cajero')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ruta_name', models.CharField(max_length=100, verbose_name='Nombre de la ruta')),
                ('comen', models.CharField(blank=True, default='none', max_length=100, verbose_name='Comentarios')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Conductores', to=settings.AUTH_USER_MODEL, verbose_name='Conductor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductByClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por cliente')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clienteOrder', to='orders.Client', verbose_name='Cliente')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_client', to='producto.Product', verbose_name='producto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('count', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('select_product', models.CharField(max_length=13, verbose_name='Especificar el tipo de pan')),
                ('price_purchase', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Precio Compra')),
                ('sub_total', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Subtotal')),
                ('price_sale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Venta')),
                ('comen', models.CharField(blank=True, default='none', max_length=100, verbose_name='Comentarios')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Impuesto')),
                ('anulate', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_sale', to='orders.Order', verbose_name='Codigo de Venta')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='producto.Product', verbose_name='producto')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rutas', to='orders.Ruta', verbose_name='Ruta')),
            ],
            options={
                'verbose_name': 'Detalle del pedido',
                'verbose_name_plural': 'Detalles de los pedidos',
            },
        ),
        migrations.CreateModel(
            name='OrderCarShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('barcode', models.CharField(max_length=13)),
                ('count', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Precio')),
                ('sub_total', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Subtotal')),
                ('number_shop', models.CharField(blank=True, choices=[('0', 'USUARIO_1'), ('1', 'USUARIO_2'), ('2', 'USUARIO_3')], default='0', max_length=2, verbose_name='USERS')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clienteOrderCarshop', to='orders.Client', verbose_name='Cliente')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_car', to='orders.ProductByClient', verbose_name='producto')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='cajero')),
            ],
            options={
                'verbose_name': 'Carrito de pedidos',
                'verbose_name_plural': 'Carrito de pedidos',
                'ordering': ['-created'],
            },
        ),
    ]
