# Generated by Django 3.0.6 on 2022-09-27 19:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_auto_20220927_1424'),
        ('orders', '0003_auto_20220906_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduceProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('count', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('produce', models.BooleanField(default=False, verbose_name='Por producir')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_produce', to='producto.Product', verbose_name='productoProduce')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
