# Generated by Django 3.0.6 on 2022-10-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20221004_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='contar',
            field=models.BooleanField(default=False, verbose_name='Por producir'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='produce',
            field=models.BooleanField(default=False, verbose_name='Por producir'),
        ),
    ]
