# Generated by Django 3.0.6 on 2022-10-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20221004_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='finish',
            field=models.BooleanField(default=False, verbose_name='pagado y entegado'),
        ),
    ]
