# Generated by Django 3.0.6 on 2022-10-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderdetail_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora del pedido'),
        ),
    ]
