# Generated by Django 3.0.6 on 2022-06-03 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_price1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='precio venta1'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='precio venta4 '),
        ),
        migrations.AddField(
            model_name='product',
            name='select_use',
            field=models.CharField(blank=True, choices=[('0', 'Más vendido'), ('1', 'Abarrotes'), ('2', 'Pan')], max_length=1, null=True, verbose_name='Orden de venta'),
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('count_product', models.PositiveIntegerField(default=0, verbose_name='Cantidad a modificar')),
                ('add_quit', models.BooleanField(default=True, verbose_name='Agregar quitar')),
                ('comment', models.CharField(choices=[('0', 'Baja de pan atrasado'), ('1', 'Baja por mala produccion'), ('2', 'Baja por consumo de personal'), ('3', 'Entrada del día'), ('4', 'Baja por cambio de pieza')], default=3, max_length=1, verbose_name='Motivo de baja o alta')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Producto', to='producto.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ingresa', to=settings.AUTH_USER_MODEL)),
                ('user_produce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Producción', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
