# Generated by Django 3.0.6 on 2022-08-03 04:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20220627_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('barcode', models.CharField(max_length=13)),
                ('count_report', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='cantidad en almacen')),
                ('count_add_report', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='cantidad contada')),
                ('count_total_report', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='cantidad sobrante o faltante')),
                ('product_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Producto_report', to='producto.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
