# Generated by Django 3.0.6 on 2022-08-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_listfinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='listfinal',
            name='product_produce',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='cantidad producida al día'),
        ),
        migrations.AlterField(
            model_name='count',
            name='comment',
            field=models.CharField(choices=[('0', 'Baja de pan atrasado'), ('1', 'Baja por mala produccion'), ('2', 'Baja por consumo de personal'), ('3', 'Entrada del día'), ('4', 'Baja por cambio de pieza'), ('5', 'Baja consumo interno'), ('6', 'Baja por ajuste de sistema'), ('7', 'Entrada por ajuste de sistema')], default=3, max_length=1, verbose_name='Motivo de baja o alta'),
        ),
    ]
