# Generated by Django 3.0.6 on 2022-08-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_auto_20220827_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='select_use',
            field=models.CharField(blank=True, choices=[('0', 'Más vendido'), ('1', 'Abarrotes'), ('2', 'Pan'), ('3', 'Lacteos'), ('4', 'Pan de Temporada')], max_length=1, null=True, verbose_name='Orden de venta'),
        ),
    ]
