# Generated by Django 3.0.6 on 2022-10-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_auto_20220927_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='porcentaje de ganancia'),
        ),
    ]
