# Generated by Django 3.0.6 on 2022-10-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0009_product_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_last',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='precio pan frio '),
        ),
        migrations.AlterField(
            model_name='count',
            name='comment',
            field=models.CharField(choices=[('0', 'Merma'), ('1', 'Baja por mala produccion'), ('2', 'Baja por consumo de personal'), ('3', 'Entrada del día'), ('4', 'Baja por cambio de pieza'), ('5', 'Baja consumo interno'), ('6', 'Baja por ajuste de sistema'), ('7', 'Entrada por ajuste de sistema'), ('8', 'Entrada de San Miguel'), ('9', 'Entrada stock de reserva')], default=3, max_length=1, verbose_name='Motivo de baja o alta'),
        ),
    ]
