version: "3.1"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: marketdb3
      POSTGRES_PASS: root
    volumes:
      - pgdata:/var/lib/posgresql/data
  market:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./market:/market
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
volumes:
  pgdata: